const { Product } = require('../models');
const productData = [{
        product_name: 'test1',
        price:45,
        description:'test1',
        stock:2,
        image:'https://underarmour.scene7.com/is/image/Underarmour/FW21_BRND_Team_Q3_Site_2_1_2?qlt=85&fmt=jpg&wid=1440&op_sharpen=1&hei=720&',
        size:'XL',
        color:'red',
        quentity:'1',
        category_id:1,
        gender_id:1,
    },
    // {
    //     product_name: '',
    //     price:,
    //     description:,
    //     stock:,
    //     image:,
    //     size:,
    //     color:,
    //     quentity:,
    //     category_id:,
    //     gender_id:,
    // },
    // {
    //     product_name: '',
    //     price:,
    //     description:,
    //     stock:,
    //     image:,
    //     size:,
    //     color:,
    //     quentity:,
    //     category_id:,
    //     gender_id:,
    // },
    // {
    //     product_name: '',
    //     price:,
    //     description:,
    //     stock:,
    //     image:,
    //     size:,
    //     color:,
    //     quentity:,
    //     category_id:,
    //     gender_id:,
    // },
    // {
    //     product_name: '',
    //     price:,
    //     description:,
    //     stock:,
    //     image:,
    //     size:,
    //     color:,
    //     quentity:,
    //     category_id:,
    //     gender_id:,
    // },
    
];
const seedProducts = () => Product.bulkCreate(productData);
module.exports = seedProducts;